/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyDropdown {
        "label"?: string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
    interface MyDropdownOption {
        "label": string;
        /**
          * @default false
         */
        "selected": boolean;
        "value": string;
    }
}
export interface MyDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyDropdownElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyDropdownElementEventMap {
        "selectionChange": string[];
    }
    interface HTMLMyDropdownElement extends Components.MyDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyDropdownElementEventMap>(type: K, listener: (this: HTMLMyDropdownElement, ev: MyDropdownCustomEvent<HTMLMyDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyDropdownElementEventMap>(type: K, listener: (this: HTMLMyDropdownElement, ev: MyDropdownCustomEvent<HTMLMyDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyDropdownElement: {
        prototype: HTMLMyDropdownElement;
        new (): HTMLMyDropdownElement;
    };
    interface HTMLMyDropdownOptionElement extends Components.MyDropdownOption, HTMLStencilElement {
    }
    var HTMLMyDropdownOptionElement: {
        prototype: HTMLMyDropdownOptionElement;
        new (): HTMLMyDropdownOptionElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-dropdown": HTMLMyDropdownElement;
        "my-dropdown-option": HTMLMyDropdownOptionElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyDropdown {
        "label"?: string;
        "onSelectionChange"?: (event: MyDropdownCustomEvent<string[]>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface MyDropdownOption {
        "label": string;
        /**
          * @default false
         */
        "selected"?: boolean;
        "value": string;
    }

    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }
    interface MyDropdownAttributes {
        "label": string;
        "size": 'sm' | 'md' | 'lg';
    }
    interface MyDropdownOptionAttributes {
        "value": string;
        "label": string;
        "selected": boolean;
    }

    interface IntrinsicElements {
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "my-dropdown": Omit<MyDropdown, keyof MyDropdownAttributes> & { [K in keyof MyDropdown & keyof MyDropdownAttributes]?: MyDropdown[K] } & { [K in keyof MyDropdown & keyof MyDropdownAttributes as `attr:${K}`]?: MyDropdownAttributes[K] } & { [K in keyof MyDropdown & keyof MyDropdownAttributes as `prop:${K}`]?: MyDropdown[K] };
        "my-dropdown-option": Omit<MyDropdownOption, keyof MyDropdownOptionAttributes> & { [K in keyof MyDropdownOption & keyof MyDropdownOptionAttributes]?: MyDropdownOption[K] } & { [K in keyof MyDropdownOption & keyof MyDropdownOptionAttributes as `attr:${K}`]?: MyDropdownOptionAttributes[K] } & { [K in keyof MyDropdownOption & keyof MyDropdownOptionAttributes as `prop:${K}`]?: MyDropdownOption[K] } & OneOf<"value", MyDropdownOption["value"], MyDropdownOptionAttributes["value"]> & OneOf<"label", MyDropdownOption["label"], MyDropdownOptionAttributes["label"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-dropdown": LocalJSX.IntrinsicElements["my-dropdown"] & JSXBase.HTMLAttributes<HTMLMyDropdownElement>;
            "my-dropdown-option": LocalJSX.IntrinsicElements["my-dropdown-option"] & JSXBase.HTMLAttributes<HTMLMyDropdownOptionElement>;
        }
    }
}
